name: Next data api id deployment - rerun

on:
  workflow_run:
    workflows: ["Actualizar precio del dolar"]
    types:
      - completed

jobs:
  BuildID:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Chequear
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Instalar Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          sudo apt-get install chromium-chromedriver

      - run: python get_id_api.py

      - id: commit
        name: Commit  files
        run: |
          git config --local user.name "action-user"
          git pull
          git config --local user.email "actions@github.com"
          git add -A
          git commit -m "Update ID deploy"
          git push origin main
        env:
          REPO_KEY: ${{ secrets.GITHUB_TOKEN }}
          username: github-actions

  rerun_action2:
    needs: BuildID
    runs-on: ubuntu-latest
    steps:
      - name: Trigger DolarPrice Workflow Again
        run: |
          echo "Re-triggering dolarPrice.yml workflow..."
          gh workflow run "dolarPrice.yml" --ref ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
